language: minimal
services:
  - docker
env:
  global:
    - VERSION="0.0.${TRAVIS_BUILD_NUMBER}"
git:
  depth: false

before_script:
  # Build local container to run terraform with
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - make docker-build

script:
  - # Run the tests
  - env
  - make run-tests ENVIRONMENT=prod

notifications:
  email:
    recipients:
    - chuesgen@gmail.com
    on_success: always
    on_failure: always
